--FARMACIA

--MEDICAMENTOS
--SUCURSAL
--CATEGORIA

CREATE DATABASE FARMACIA

USE FARMACIA

--TABLA SUCURSAL (FARMACIAS)
CREATE TABLE SUCURSAL(
	ID INT IDENTITY PRIMARY KEY,			--ID
	NOMBRE VARCHAR(50) NOT NULL,			--NOMBRE DE SUCURSAL
	UBICACION VARCHAR(150) NOT NULL,		--UBICACION
	CORREO VARCHAR(30) NOT NULL,			--CORREO ELECTRONICO
	TELEFONO VARCHAR(12) NOT NULL			--NUMERO DE TELEFONO
)

--TABLA CATEGORIA DE PRODUCTO
CREATE TABLE CATEGORIA(
	ID INT IDENTITY PRIMARY KEY,			--ID
	DESCRIPCION VARCHAR(50) NOT NULL		--DESCRIPCION
)

--TABLA MEDICAMENTOS
CREATE TABLE MEDICAMENTO(
	ID INT IDENTITY PRIMARY KEY,			--ID
	PRECIO FLOAT NOT NULL DEFAULT(0.0),		--PRECIO
	ID_CATEGORIA INT NOT NULL				--CATEGORIA
	
	CONSTRAINT FKIDCATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID)
)

--TABLA MEDICAMENTO Y SUCURSAL (UBICACION)
CREATE TABLE MEDICAMENTO_SUCURSAL(
	ID_MEDICAMENTO INT,						--MEDICAMENTO
	ID_SUCURSAL INT,						--SUCURSAL
	CANTIDAD INT NULL DEFAULT(0),			--CANTIDAD
	
	CONSTRAINT FKIDMEDICAMENTO FOREIGN KEY(ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID),
	CONSTRAINT FKIDSUCURSAL FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID)
)

